[workspace]
git_only = true
git_release_enable = false
git_tag_enable = false
release_always = false
git_tag_name = "v{{ version }}"
dependencies_update = false
features_always_increment_minor = true
